-- MySQL Script generated by MySQL Workbench
-- Mon Sep 18 15:00:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo` (
  `idtipo` INT UNSIGNED NOT NULL,
  `detipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtipo_UNIQUE` ON `tipo` (`idtipo` ) ;

CREATE UNIQUE INDEX `detipo_UNIQUE` ON `tipo` (`detipo` ) ;


-- -----------------------------------------------------
-- Table `tensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tensao` (
  `idtensao` INT UNSIGNED NOT NULL,
  `detensao` VARCHAR(50) NULL,
  PRIMARY KEY (`idtensao`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtensao_UNIQUE` ON `tensao` (`idtensao` ) ;

CREATE UNIQUE INDEX `detensao_UNIQUE` ON `tensao` (`detensao` ) ;


-- -----------------------------------------------------
-- Table `espaco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espaco` (
  `idespaco` INT UNSIGNED NOT NULL,
  `deespaco` VARCHAR(10) NULL,
  PRIMARY KEY (`idespaco`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idespaco_UNIQUE` ON `espaco` (`idespaco` ) ;

CREATE UNIQUE INDEX `deespaco_UNIQUE` ON `espaco` (`deespaco` ) ;


-- -----------------------------------------------------
-- Table `gaveta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaveta` (
  `idgaveta` INT UNSIGNED NOT NULL,
  `degaveta` VARCHAR(10) NULL,
  PRIMARY KEY (`idgaveta`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idgaveta_UNIQUE` ON `gaveta` (`idgaveta` ) ;

CREATE UNIQUE INDEX `degaveta_UNIQUE` ON `gaveta` (`degaveta` ) ;


-- -----------------------------------------------------
-- Table `componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `componente` (
  `idcomponente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nmcomponente` VARCHAR(200) NOT NULL,
  `idtipo` INT UNSIGNED NOT NULL,
  `idtensao` INT UNSIGNED NOT NULL,
  `idespaco` INT UNSIGNED NOT NULL,
  `idgaveta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcomponente`),
  CONSTRAINT `fk_componente_tipo`
    FOREIGN KEY (`idtipo`)
    REFERENCES `tipo` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_componente_tensao1`
    FOREIGN KEY (`idtensao`)
    REFERENCES `tensao` (`idtensao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_componente_espaco1`
    FOREIGN KEY (`idespaco`)
    REFERENCES `espaco` (`idespaco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_componente_gaveta1`
    FOREIGN KEY (`idgaveta`)
    REFERENCES `gaveta` (`idgaveta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcomponente_UNIQUE` ON `componente` (`idcomponente` ) ;

CREATE UNIQUE INDEX `nmcomponente_UNIQUE` ON `componente` (`nmcomponente` ) ;

CREATE INDEX `fk_componente_tipo_idx` ON `componente` (`idtipo` ) ;

CREATE INDEX `fk_componente_tensao1_idx` ON `componente` (`idtensao` ) ;

CREATE INDEX `fk_componente_espaco1_idx` ON `componente` (`idespaco` ) ;

CREATE INDEX `fk_componente_gaveta1_idx` ON `componente` (`idgaveta` ) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





